// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixedforeignkeystovirutaloncharacter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedforeignkeystovirutaloncharacter));
        
        string IMigrationMetadata.Id
        {
            get { return "202006042312410_fixed foreignkeys to virutal on character"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
